In [1]:
import os
import math
import numpy as np
import time

## Imports for plotting
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg', 'pdf') # For export
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()

## Progress bar
from tqdm.notebook import tqdm

/tmp/ipykernel_30238/1667656876.py:10: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats('svg', 'pdf') # For export


In [2]:
import torch
print("Using torch", torch.__version__)
torch.manual_seed(42) # Setting the seed


Using torch 1.9.0


Basic Operation of Pytorch

In [5]:
x = torch.Tensor(2, 3)
print(x)

# Create a tensor from a (nested) list
x = torch.Tensor([[1, 2], [3, 4]])
print(x)

# Create a tensor with random values between 0 and 1 with the shape [2, 3, 4]
x = torch.rand(2, 3)
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[0.3060, 0.7339, 0.3567],
        [0.7144, 0.8998, 0.1846]])


In [6]:
shape = x.shape
print("Shape:", x.shape)

size = x.size()
print("Size:", size)

dim1, dim2 = x.size()
print("Size:", dim1, dim2)

Shape: torch.Size([2, 3])
Size: torch.Size([2, 3])
Size: 2 3


In [7]:
np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]])


In [8]:
tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


In [9]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
y = x1 + x2

print("X1", x1)
print("X2", x2)
print("Y", y)

X1 tensor([[0.3005, 0.9988, 0.1956],
        [0.4901, 0.4828, 0.5518]])
X2 tensor([[0.3324, 0.6651, 0.3022],
        [0.4546, 0.6768, 0.0589]])
Y tensor([[0.6330, 1.6639, 0.4977],
        [0.9447, 1.1597, 0.6107]])


In [10]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
print("X1 (before)", x1)
print("X2 (before)", x2)

x2.add_(x1)#inplace_operation
print("X1 (after)", x1)
print("X2 (after)", x2)

X1 (before) tensor([[0.7319, 0.1614, 0.9744],
        [0.8307, 0.1488, 0.8748]])
X2 (before) tensor([[0.4260, 0.0113, 0.4617],
        [0.4497, 0.9561, 0.7601]])
X1 (after) tensor([[0.7319, 0.1614, 0.9744],
        [0.8307, 0.1488, 0.8748]])
X2 (after) tensor([[1.1579, 0.1727, 1.4361],
        [1.2804, 1.1049, 1.6348]])


Multiple

In [12]:
x = torch.arange(6)
x = x.view(2, 3)
print("X", x)

W = torch.arange(9).view(3, 3) # We can also stack multiple operations in a single line
print("W", W)

h = torch.matmul(x, W) # Verify the result by calculating it by hand too!
print("h", h)

X tensor([[0, 1, 2],
        [3, 4, 5]])
W tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
h tensor([[15, 18, 21],
        [42, 54, 66]])


Indexing

In [13]:
x = torch.arange(12).view(3, 4)
print("X", x)

print(x[:, 1])   # Second column

print(x[1:3, :]) # Middle two rows

X tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([1, 5, 9])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


Dynamic Computation Graph and Backpropagation

In [14]:
x = torch.ones((3,))
print(x.requires_grad)

x.requires_grad_(True)
print(x.requires_grad)

False
True


In [15]:
x = torch.arange(3, dtype=torch.float32, requires_grad=True) # Only float tensors can have gradients
print("X", x)

X tensor([0., 1., 2.], requires_grad=True)


$y= \sum_{i}\left[\left(x_{i}+4\right)^{3}+10\right]$

In [17]:
a = x + 4
b = a ** 3
c = b + 10
y = c.sum()
print("Y", y)

Y tensor(435., grad_fn=<SumBackward0>)


In [18]:
y.backward()
print(x.grad)

tensor([ 48.,  75., 108.])
